name: "Static Analysis"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          path: src/